Voka\VokaBundle\Document\Vocabel:
    fields:
        id:
            id: true
            type: string
            strategy: NONE
        officialName:
            type: string
        officialLanguage:
            type: string
        currency:
            type: string
        sharesBorderWith:
            type: collection
        topLevelDomain:
            type: string
        population:
            type: int
        capital:
            type: string
        continent:
            type: string
        rand:
            type: float
